// TourPack injection proxy — serves the REAL app and injects the tour.
// Generated by generate-proxy.sh for localhost:3000
const http = require('http');
const zlib = require('zlib');
const fs = require('fs');
const path = require('path');

const UPSTREAM = { host: 'localhost', port: 3000 };
const PORT = 8932;

// Tour assets — default to ../tour-overlay.* (shared pack), override if needed
const TOUR_JS = process.env.TOUR_JS   || path.join(__dirname, '..', 'tour-overlay.js');
const TOUR_CSS = process.env.TOUR_CSS || path.join(__dirname, '..', 'tour-overlay.css');
const TOUR_CFG = process.env.TOUR_CFG || path.join(__dirname, '..', 'tour-config.js');

function injectScript(html) {
  const css  = '<link rel="stylesheet" href="/__tour/tour-overlay.css">';
  const js   = '<script src="/__tour/tour-config.js" defer></script><script src="/__tour/tour-overlay.js" defer></script>';
  if (html.includes('</body>')) return html.replace('</body>', css + js + '\n</body>');
  return html + css + js;
}

function decompress(buf, encoding) {
  return new Promise((resolve, reject) => {
    if (!encoding || encoding === 'identity') return resolve(buf);
    let stream;
    if (encoding.includes('gzip')) stream = zlib.gunzip;
    else if (encoding.includes('br')) stream = zlib.brotliDecompress;
    else if (encoding.includes('deflate')) stream = zlib.inflate;
    else return resolve(buf);
    stream(buf, (err, out) => (err ? reject(err) : resolve(out)));
  });
}

const TOUR_FILES = {
  'tour-overlay.css': TOUR_CSS,
  'tour-overlay.js':  TOUR_JS,
  'tour-config.js':   TOUR_CFG,
};

const server = http.createServer((req, res) => {
  const url = req.url;

  // Serve tour assets directly (never compressed)
  if (url.startsWith('/__tour/')) {
    const name = url.replace('/__tour/', '');
    const file = TOUR_FILES[name];
    if (file && fs.existsSync(file)) {
      const ext = path.extname(file);
      const type = ext === '.css' ? 'text/css' : ext === '.json' ? 'application/json' : 'application/javascript';
      res.writeHead(200, { 'Content-Type': type, 'Cache-Control': 'no-store', 'Content-Length': fs.statSync(file).size });
      res.end(fs.readFileSync(file));
      return;
    }
    res.writeHead(404); res.end();
    return;
  }

  // Proxy to upstream
  const proxyReq = http.request({
    host: UPSTREAM.host,
    port: UPSTREAM.port,
    path: url,
    method: req.method,
    headers: { ...req.headers, host: `localhost:${UPSTREAM.port}`, 'accept-encoding': 'gzip, br' },
  }, (proxyRes) => {
    const chunks = [];
    proxyRes.on('data', c => chunks.push(c));
    proxyRes.on('end', async () => {
      try {
        const buf = Buffer.concat(chunks);
        const ctype = proxyRes.headers['content-type'] || '';
        const enc = proxyRes.headers['content-encoding'] || '';
        let body = buf;
        let finalHeaders = { ...proxyRes.headers };
        if (ctype.includes('text/html')) {
          const plain = enc ? await decompress(buf, enc) : buf;
          const injected = injectScript(plain.toString('utf8'));
          body = Buffer.from(injected, 'utf8');
          delete finalHeaders['content-encoding'];
          delete finalHeaders['transfer-encoding'];
        }
        delete finalHeaders['content-length'];
        finalHeaders['cache-control'] = 'no-store';
        res.writeHead(proxyRes.statusCode || 200, finalHeaders);
        res.end(body);
      } catch (e) {
        res.writeHead(502, { 'Content-Type': 'text/plain' });
        res.end('Proxy error: ' + e.message);
      }
    });
  });
  proxyReq.on('error', (e) => {
    res.writeHead(502, { 'Content-Type': 'text/plain' });
    res.end('Upstream app not reachable on localhost:3000 — ' + e.message);
  });
  req.pipe(proxyReq);
});

server.listen(PORT, '0.0.0.0', () => {
  console.log('TourPack proxy: http://0.0.0.0:' + PORT + ' → localhost:3000');
});
